### ISSUE TITLE
Not available via npm

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [SvanBoxel/visibility-sensor-react-native#1]
The package is not available via npm install

**Comment by bramski** [comment]
Poke Poke @SvanBoxel.

**Comment by SvanBoxel** [comment]
![](https://media.giphy.com/media/PkR8gPgc2mDlrMSgtu/giphy.gif) @bramski 

Issue confirmed. Let me check what's going on and come back to you this week.

**Comment by jeanjs** [comment]
Hello! any updates on this?

**Comment by SvanBoxel** [comment]
Hey! Does this work for you? 

`npm i @svanboxel/visibility-sensor-react-native`

**Comment by mariomurrent-softwaresolutions** [comment]
Seems to work now, thx
