### ISSUE TITLE
Sometimes not working when scrolling down with videos

### ISSUE THREAD

**Issue by ursnj** [SvanBoxel/visibility-sensor-react-native#3]
Im trying to implement video timeline on top of this library, its working in most cases but in few cases its not triggering on focus out from window viewport.

**Comment by SvanBoxel** [comment]
Hmm that surprises me. Do you have some example code or a screen record of when this happens?

**Comment by ursNj** [comment]
Im using this package to play  pause videos on timeline, but i can see its failing in few cases. will try to provide some demo video.

When we scroll fast or if we keep Scrollview and flatlist in the same page its not working every time, but 70% times its working but fails 30%.

**Comment by SvanBoxel** [comment]
Thanks for sharing this information. Another option is to share an [Expo Snack](https://snack.expo.io/) with code that reproduces the issue.

**Comment by liquidvisual** [comment]
@ursNj I'm doing something similar with video. Were you ever successful with this library?

**Comment by MujahidMansuri** [comment]
@SvanBoxel in my case does not work,

**Comment by ursnj** [comment]
@liquidvisual i have extended this lib and fixed all issues. check the source you can able adjust settings

**Comment by MujahidMansuri** [comment]
@liquidvisual could you send the example of it?

Thanks in advance!

**Comment by Robebou** [comment]
@ursnj Could you push or send the modifications ? Cant make it work with videos
Tanks

**Comment by SvanBoxel** [comment]
@ursnj Could you perhaps open a pull request so everyone can leverage these improvements? Thank you!

**Comment by suyashvash** [comment]
Just Fixed This issue in my latest PR, it will return isVisble to false and then you can put that value in your video player as prop.... Just did it in mine

**Comment by suyashvash** [comment]
> Just Fixed This issue in my latest PR, it will return isVisble to false and then you can put that value in your video player as prop.... Just did it in mine

It was a quick fix as `else { props.onChange(isVisible) }` in index file .... it was sending the true value when in view but not the false if outside the view

**Comment by SvanBoxel** [comment]
Fixed in https://github.com/SvanBoxel/visibility-sensor-react-native/pull/10 by @suyashvash 🙇🏽
